let g:config_dir = '~/.vim/config/'

let g:config_files = [
      \ 'custom.vim',
      \ 'fzf.vim',
      \ 'mappings.vim',
      \ 'settings.vim',
      \ 'startscreen.vim',
      \ 'airline.vim',
      \ 'fastfold.vim',
      \ 'coc.vim',
      \ 'sneak.vim',
      \ ]

for config_file in g:config_files
  let full_path = expand(g:config_dir . config_file)

  if filereadable(full_path)
    execute 'source ' . full_path
  else
    echo "Warning: Configuration file " . full_path . " not found"
  endif
endfor
