#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
BAR_HEIGHT=32
FONT_SIZE=14
LABEL_FONT_SIZE=13
SPACE_PADDING=12
ITEM_PADDING=6

sketchybar --bar height=$BAR_HEIGHT \
  blur_radius=0 \
  position=top \
  sticky=on \
  padding_left=10 \
  padding_right=10 \
  color=0xff000000 \
  shadow=off \
  topmost=on

sketchybar --default updates=when_shown \
  icon.font="CaskaydiaCove NF:Bold:${FONT_SIZE}.0" \
  icon.color=0xffffffff \
  icon.padding_left=$ITEM_PADDING \
  icon.padding_right=$ITEM_PADDING \
  icon.y_offset=0 \
  label.font="CaskaydiaCove NF:Bold:${LABEL_FONT_SIZE}.0" \
  label.color=0xffffffff \
  label.padding_left=$ITEM_PADDING \
  label.padding_right=$ITEM_PADDING \
  label.y_offset=0 \
  background.padding_left=2 \
  background.padding_right=2

SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")

for i in "${!SPACE_ICONS[@]}"
do
  sid=$(($i+1))
  sketchybar --add space space.$sid left \
    --set space.$sid associated_space=$sid \
    icon=${SPACE_ICONS[i]} \
    icon.padding_left=$SPACE_PADDING \
    icon.padding_right=$SPACE_PADDING \
    icon.y_offset=0 \
    label.padding_right=0 \
    label.drawing=off \
    background.color=0xff1a1a1a \
    background.corner_radius=0 \
    background.height=$BAR_HEIGHT \
    background.drawing=on \
    script="$PLUGIN_DIR/space.sh" \
    click_script="yabai -m space --focus $sid"
  done

  sketchybar --add item separator_l left \
    --set separator_l icon="|" \
    icon.padding_left=12 \
    icon.padding_right=0 \
    background.drawing=off

  sketchybar --add item window_title left \
    --set window_title script="$PLUGIN_DIR/window_title.sh" \
    icon.drawing=off \
    label.font="CaskaydiaCove NF:Regular:${LABEL_FONT_SIZE}.0" \
    label.padding_left=0 \
    label.padding_right=4 \
    --subscribe window_title front_app_switched


  sketchybar --add item clock right \
    --set clock update_freq=1 \
    icon="" \
    script="$PLUGIN_DIR/clock.sh" \
    background.drawing=off \
    icon.padding_left=4 \
    icon.padding_right=2 \
    label.padding_left=2 \
    label.padding_right=8

  sketchybar --add item separator_r1 right \
    --set separator_r1 icon="|" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    background.drawing=off

  sketchybar --add item battery right \
    --set battery update_freq=10 \
    icon="BAT" \
    script="$PLUGIN_DIR/battery.sh" \
    background.drawing=off \
    icon.padding_left=4 \
    icon.padding_right=2 \
    label.padding_left=2 \
    label.padding_right=4

  sketchybar --add item separator_r2 right \
    --set separator_r2 icon="|" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    background.drawing=off

  sketchybar --add item vpn right \
    --set vpn update_freq=5 \
    icon="VPN" \
    script="$PLUGIN_DIR/vpn.sh" \
    background.drawing=off \
    icon.padding_left=4 \
    icon.padding_right=2 \
    label.padding_left=2 \
    label.padding_right=4

  sketchybar --add item separator_r3 right \
    --set separator_r3 icon="|" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    background.drawing=off

  sketchybar --add item spotify right \
    --set spotify update_freq=2 \
    icon="♫" \
    script="$PLUGIN_DIR/spotify.sh" \
    background.drawing=off \
    icon.padding_left=8 \
    icon.padding_right=2 \
    label.padding_left=2 \
    label.padding_right=4 \
    --subscribe spotify system_woke

  sketchybar --update
