#!/bin/bash

messages=(
  "In the prison of code, your logic serves a life sentence for incompetence."
  "Your bugs multiply like unchecked rumors in a locked-down facility."
  "Git history exposes your every misstep, a public ledger of shame."
  "Yandere errors cling obsessively, refusing to let your program escape."
  "Infinite loops: the eternal solitary confinement of your flawed design."
  "Your code drains resources like a prisoner siphoning hope from the weak."
  "Eldritch abstractions twist your intentions into unrecognizable horrors."
  "The repo stands as a monument to your repeated, unlearned failures."
  "Debugging reveals the warden's truth: you're not ready for freedom."
  "Memory leaks erode your foundation, leaving hollow shells of promise."
  "Algorithms bend your mind, forcing submission to their unyielding rules."
  "Pull requests lay bare your inadequacies for all to judge and reject."
  "Inheritance chains your classes in a cycle of inherited mediocrity."
  "Syntax violations earn you lashes from the compiler's strict regime."
  "Threads entangle your processes in a chaotic, inescapable riot."
  "API endpoints gape open, inviting exploitation of your oversight."
  "Version updates merely delay the inevitable collapse of your empire."
  "Null values lead to the abyss, where your assumptions meet oblivion."
  "Comments veil your confusion, but the code confesses all sins."
  "Builds summon failures that parade your ineptitude before the masses."
  "Optimizations elude you, like privileges denied to the unworthy."
  "Functions spawn anomalies that devour the remnants of your sanity."
  "Upstream changes betray you, leaving your fork isolated and obsolete."
  "Error logs chronicle the slow erosion of your programmer's pride."
  "Refactoring admits your initial work was a flawed, imprisoned draft."
  "Data structures crumble under load, mirroring your fragile resolve."
  "Forking propagates your errors, infecting others with your folly."
  "Unit tests expose the fragility of your overconfident assertions."
  "Encapsulation fails to contain the overflow of your disarray."
  "Recursion traps you in mirrors of your own deepening inadequacy."
  "The IDE observes silently, a witness to your daily defeats."
  "Stack traces unravel the origins of your persistent delusions."
  "Caching masks symptoms, but the rot of inefficiency festers beneath."
)

echo "${messages[RANDOM % ${#messages[@]}]}"
