highlight CocFloating ctermbg=NONE ctermfg=15
highlight CocMenuSel ctermbg=NONE ctermfg=5
highlight CocErrorFloat ctermbg=NONE ctermfg=1
highlight CocWarningFloat ctermbg=NONE ctermfg=3
highlight CocInfoFloat ctermbg=NONE ctermfg=7
highlight CocHintFloat ctermbg=NONE ctermfg=7
highlight CocCursorRange ctermbg=NONE ctermfg=5
highlight CocBorder ctermbg=NONE ctermfg=0
highlight CocPrompt ctermbg=NONE ctermfg=6
