hi CocFloating ctermbg=NONE ctermfg=15
hi CocMenuSel ctermbg=NONE ctermfg=5
hi CocErrorFloat ctermbg=NONE ctermfg=1
hi CocWarningFloat ctermbg=NONE ctermfg=3
hi CocInfoFloat ctermbg=NONE ctermfg=7
hi CocHintFloat ctermbg=NONE ctermfg=7
hi CocCursorRange ctermbg=NONE ctermfg=5
hi CocBorder ctermbg=NONE ctermfg=0
hi CocPrompt ctermbg=NONE ctermfg=6
