set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",wezterm*:Tc"
set -ga terminal-overrides ",xterm-256color:Tc"

unbind C-b
set -g prefix C-t
bind C-t send-prefix

set-option -g history-limit 50000
set-option -g initial-repeat-time 500
set-option -g display-time 4000
set-option -g renumber-windows on

bind c new-window -c "~"
bind '"' split-window -c "~"
bind % split-window -h -c "~"

setw -g mode-keys vi

bind -T copy-mode-vi 'v' send -X begin-selection

bind-key -n M-r source-file "$HOME/.config/tmux/tmux.conf" \; display "Reloaded!"
bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R
bind-key -n M-Left resize-pane -L 5
bind-key -n M-Right resize-pane -R 5
bind-key -n M-Up resize-pane -U 5
bind-key -n M-Down resize-pane -D 5
bind-key -n M-[ copy-mode
bind-key -n M-d detach-client
bind-key -n M-w choose-tree -Z
bind-key -n M-n next-window
bind-key -n M-p previous-window
bind-key -n M-z resize-pane -Z

bind-key C-f run-shell "tmux display-popup -E -w 80% -h 80% -b none 'TMUX_PANE=#{pane_id} ~/.scripts/tmux_file_picker.sh'"

source-file ~/.config/tmux/snapshot.conf

set -g @continuum-restore 'on'
set -g @continuum-boot 'on'
set -g @continuum-boot-options 'wezterm,fullscreen'
set -g @continuum-save-interval 15

run-shell "$HOME/.config/tmux/plugins/tmux-now-playing/now-playing.tmux"
run-shell "$HOME/.config/tmux/plugins/tmux-yank/yank.tmux"
run-shell "$HOME/.config/tmux/plugins/tmux-copycat/copycat.tmux"
run-shell "$HOME/.config/tmux/plugins/tmux-resurrect/resurrect.tmux"
